### ISSUE TITLE
quickstart samplescript_coron.json dependence

### ISSUE THREAD

**Issue by turmon** [dsavransky/EXOSIMS#100]
The quickstart guide gives "EXOSIMS/Scripts/sampleScript_coron.json" as the default starting script.  This script uses:
   "PlanetPhysicalModel": "Forecaster",
which takes a dependence on a 94MB HDF file from another GitHub repo, plus an h5 reader.  The error message thrown when the HDF file is not present is non-obvious.

Could we replace Forecaster with FortneyMarleyCahoyMix1 (within Scripts/sampleScript*.json) or use another workaround to cut this dependence?

**Comment by dsavransky** [comment]
Both sampleScripts have been updated.
