### ISSUE TITLE
genOutSpec error on write to file

### ISSUE THREAD

**Issue by rhondamorgan** [dsavransky/EXOSIMS#110]
I have attempted with v1.33, v1.3, and clones from 20170806 and 20170816 with the same error.
I have used both commands with the same result: 
 sim.SurveySimulation.genOutSpec(tofile='tmp.spc')
sim.SurveySimulation.genOutSpec('tmp.spc')
Here is the traceback:

In [6]: sim.SurveySimulation.genOutSpec(tofile='tmp.spc')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-9c2c5e9ae882> in <module>()
----> 1 sim.SurveySimulation.genOutSpec(tofile='tmp.spc')

/proj/exep/rhonda/exosims20170816/EXOSIMS/EXOSIMS/Prototypes/SurveySimulation.pyc in genOutSpec(self, tofile)
   1144             with open(tofile, 'w') as outfile:
   1145                 json.dump(out, outfile, sort_keys=True, indent=4, ensure_ascii=False,
-> 1146                         separators=(',', ': '), default=array_encoder)
   1147 
   1148         return out

/usr/local/python-2.7.9/lib/python2.7/json/__init__.pyc in dump(obj, fp, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, encoding, default, sort_keys, **kw)
    187     # could accelerate with writelines in some versions of Python, at
    188     # a debuggability cost
--> 189     for chunk in iterable:
    190         fp.write(chunk)
    191 

/usr/local/python-2.7.9/lib/python2.7/json/encoder.pyc in _iterencode(o, _current_indent_level)
    432                 yield chunk
    433         elif isinstance(o, dict):
--> 434             for chunk in _iterencode_dict(o, _current_indent_level):
    435                 yield chunk
    436         else:

/usr/local/python-2.7.9/lib/python2.7/json/encoder.pyc in _iterencode_dict(dct, _current_indent_level)
    406                 else:
    407                     chunks = _iterencode(value, _current_indent_level)
--> 408                 for chunk in chunks:
    409                     yield chunk
    410         if newline_indent is not None:

/usr/local/python-2.7.9/lib/python2.7/json/encoder.pyc in _iterencode_dict(dct, _current_indent_level)
    406                 else:
    407                     chunks = _iterencode(value, _current_indent_level)
--> 408                 for chunk in chunks:
    409                     yield chunk
    410         if newline_indent is not None:

/usr/local/python-2.7.9/lib/python2.7/json/encoder.pyc in _iterencode(o, _current_indent_level)
    440                     raise ValueError("Circular reference detected")
    441                 markers[markerid] = o
--> 442             o = _default(o)
    443             for chunk in _iterencode(o, _current_indent_level):
    444                 yield chunk

/proj/exep/rhonda/exosims20170816/EXOSIMS/EXOSIMS/Prototypes/SurveySimulation.pyc in array_encoder(obj)
   1189     # nothing worked, bail out
   1190 
-> 1191     return json.JSONEncoder.default(obj)

TypeError: unbound method default() must be called with JSONEncoder instance as first argument (got EXOCAT1 instance instead)

**Comment by dsavransky** [comment]
Addressed by #111
