### ISSUE TITLE
Quickstart's sampleScript_coron.json missing

### ISSUE THREAD

**Issue by douglase** [dsavransky/EXOSIMS#12]
The quickstart guide in  documentation/quickstart.rst calls Scripts/sampleScript_coron.json but  the  sample file is missing from the directory, while there are several json templates which seem to run fine. Should the sample just be replaced with one of the other templates in the guide?

**Comment by dsavransky** [comment]
Good point.  The sample scripts currently on github could use an overall cleanup as well.

**Comment by ChrisDelaX** [comment]
All scripts have been updated. 
sampleScript_coron.json is back online.
