### ISSUE TITLE
ZodiacalLight wavelength dependence

### ISSUE THREAD

**Issue by dsavransky** [dsavransky/EXOSIMS#130]
Needs to be checked for both local and exo-zodi.

**Comment by deanthedream** [comment]
Local Zodiacal light is dependent upon wavelength. however, exo-zodi is not wavelength dependent.

**Comment by deanthedream** [comment]
@dsavransky What exo-zodi wavelength dependence is desired? What model do we implement?

**Comment by dsavransky** [comment]
This is now fully implemented in prototype and `Stark` ZodiacalLight implementation.
