### ISSUE TITLE
completeness_specs not used in comp.comp_per_inttime

### ISSUE THREAD

**Issue by rhondamorgan** [dsavransky/EXOSIMS#137]
In running the tiered scheduler with the AlbedobyRadius(inherits from SAG13) and completeness_specs with EarthtwinHabZone1, the completeness curves generated by comp.comp_per_inttime look like curves for the SAG13 distribution, not earthtwins.  This is causing very short characterization times in the tiered scheduler (~1e-5 days) and consequently char_status = 0 always. I suspect that comp.comp_per_intime is utilizing the simulation planetPop, not the completeness_specs planetPop.

**Comment by walker-dula** [comment]
What I am seeing when I access the curves being used are unchanging completeness values over the whole of the intTime range. 1e-5 days is the lowest possible intTime in this range, and so, since the completeness doesn't change, that intTime is chosen.

**Comment by dgarrett622** [comment]
It looks like Completeness loads the correct PlanetPopulation, so comp_per_intTime is using the correct PlanetPopulation data. Which completeness module are you using and what is your intTime range?

**Comment by dsavransky** [comment]
Is it possible that there is a caching issue involved?  That is, have we verified that the presence of the completeness_spec in the script correctly produces a different cache filename from the default?

**Comment by dgarrett622** [comment]
The filename is generated after Completeness instantiates the PlanetPopulation module, so it picks up whichever PlanetPopulation is used for completeness calcs. If a PlanetPopulation is specified in completeness_spec, it will be used in the filename.

**Comment by dgarrett622** [comment]
@walker-dula can you send me the script you are using and the values you are using to generate the completeness vs intTime curve?

**Comment by walker-dula** [comment]
Here is the code block from the Tiered Scheduler:

        OS = self.OpticalSystem
        Comp = self.Completeness
        TL = self.TargetList
        ZL = self.ZodiacalLight
        Obs = self.Observatory

        num_points = 500
        intTimes = np.logspace(-5, 2, num_points)*u.d
        sInds = np.arange(TL.nStars)
        WA = self.WAint[0]   # don't use WA input because we don't know planet positions before characterization
        curve = np.zeros([1, sInds.size, intTimes.size])

        Cpath = os.path.join(Comp.classpath, Comp.filename+'.fcomp')

        # if no preexisting curves exist, either load from file or calculate
        if self.curves is None:
            if os.path.exists(Cpath):
                print 'Loading cached completeness file from "%s".' % Cpath
                curves = pickle.load(open(Cpath, 'rb'))
                print 'Completeness curves loaded from cache.'
            else:
                # calculate completeness curves for all sInds
                print 'Cached completeness file not found at "%s".' % Cpath
                print 'Beginning completeness curve calculations.'
                curves = {}
                fZ = ZL.fZ(Obs, TL, sInds, startTime, mode)
                for t_i, t in enumerate(intTimes):
                    curve[0,:,t_i] = Comp.comp_per_intTime(t, TL, sInds, fZ, fEZ, WA, mode)
                curves[mode['systName']] = curve
                pickle.dump(curves, open(Cpath, 'wb'))
                print 'completeness curves stored in %r' % Cpath

            self.curves = curves

**Comment by rhondamorgan** [comment]
{
  "missionLife": 5.0,
  "missionStart": 64571,
  "missionPortion": 0.75,
  "minComp": 0.01,
  "pupilDiam": 4,
  "obscurFac": 0,
  "dMagLim": 25.5,
  "koAngleMin": 40,
  "koAngleMax": 83,
  "koAngleMinMoon": 1,
  "koAngleMinEarth": 1,
  "intCutoff": 60.0,
  "dMagint": 24,
  "WAint":0.2,
  "dMag0":24,
  "WA0":0.2,
  "charMargin": 0.12,
  "nVisitsMax":8,

  "settlingTime": 0.042, 
  "thrust": 1040,
  "slewIsp": 3000,
  "scMass": 13000,
  "dryMass": 6120,
  "coMass":5800,
  "occulterSep":124000,
  "skIsp": 308,
  "defburnPortion":0.85,
  
  "ppFact": 0.09,
  "erange": [0,0],
  "arange":[0.09, 12.4],
  "Rprange":[0.5, 11.6],
  "scaleOrbits": false,
  "constrainOrbits": true,
  "keepStarCatalog": true,
  "fillPhotometry": true,
  "explainFiltering": true,

  "occHIPs":"top40DD9stars_4m_VC6_20170420_pp.txt",
  "topstars":9,  

  "scienceInstruments": [
    {
      "name": "imagingEMCCD",
      "QE": 0.9,
      "optics": 0.28,
      "FoV": 0.75,
      "pixelNumber": 105,
      "pixelSize": 13e-6,
      "core_platescale": 0.1,
      "sread": 0,
      "idark": 3e-5,
      "CIC": 1.3e-3,
      "texp": 100,
      "ENF": 1,
      "PCeff": 0.9
    },
    {
      "name": "imagingRedEMCCD",
      "QE": 0.9,
      "optics": 0.42,
      "FoV": 1.1,
      "pixelNumber": 104,
      "pixelSize": 13e-6,
      "core_platescale": 0.1,
      "sread": 0,
      "idark": 3e-5,
      "CIC": 1.3e-3,
      "texp": 100,
      "PCeff": 0.9,
      "ENF": 1
    },
    {
      "name": "spectroEMCCD",
      "QE": 0.9,
      "FoV": 0.8,
      "optics": 0.27,
      "pixelNumber": 102,
      "pixelSize": 12e-6,
      "core_platescale": 0.1,
      "lenslSamp": 2,
      "sread": 0,
      "idark": 3e-5,
      "CIC": 2.1e-3,
      "texp": 300,
      "ENF": 1,
      "Rs": 140,
      "PCeff": 0.9
    }
  ],
  "starlightSuppressionSystems": [
    {
      "name": "VVC500",
      "lam": 500,
      "IWA": 0.045,
      "OWA": 2.127,
      "ohTime": 0.1,
      "BW": 0.20,
      "optics": 1,
      "core_platescale": 0.1,
      "occ_trans": "/proj/exep/rhonda/HabEx/G_VC6_occ_trans_asec.fits",
      "core_thruput": "/proj/exep/rhonda/HabEx/G_VC6_core_thruput_asec.fits", 
      "core_mean_intensity": "/proj/exep/rhonda/HabEx/G_VC6_core_mean_intensity_asec.fits",
      "occ_trans_local": "/Users/rhonda/exo_scripts/HabEx_Vortex/_VC6_N4096_IWA3_OWA10_circ_none_LSin0_LSout0.99_1000pix_0cm_fullDH/BW20/G_VC6_occ_trans_asec.fits",
      "core_thruput_local": "/Users/rhonda/exo_scripts/HabEx_Vortex/_VC6_N4096_IWA3_OWA10_circ_none_LSin0_LSout0.99_1000pix_0cm_fullDH/BW20/G_VC6_core_thruput_asec.fits", 
      "core_mean_intensity_local": "/Users/rhonda/exo_scripts/HabEx_Vortex/_VC6_N4096_IWA3_OWA10_circ_none_LSin0_LSout0.99_1000pix_0cm_fullDH/BW20/G_VC6_core_mean_intensity_asec.fits"

    },
    {
      "name": "Occulter_testcase",
      "occulter": true,

      "lam": 650,
      "IWA": 0.06,
      "OWA": 5.9,
      "ohTime": 0.0,
      "BW": 1.08,
      "optics": 1,
      "occ_trans": 0.6,
      "occulterDiameter": 72,
      "NocculterDistances" :1,
      "occulterDistances": [
        {
        "occulterDistance": 124000,
        "occulterRedEdge": 1000,
        "occulterBlueEdge": 300
        }
      ],
      "core_thruput": 0.7, 
      "core_contrast": 1e-10
    }
 ],
      "observingModes": [
    {
      "instName": "imagingEMCCD",
      "systName": "VVC500",
      "detection": 1,
      "SNR": 7
    },
    {
      "instName": "imagingRedEMCCD",
      "systName": "VVC500",
      "detection": 1,
      "lam": 745,
      "SNR": 7
    },
    {
      "instName": "spectroEMCCD",
      "systName": "Occulter_testcase",
      "SNR": 10
    }
  ],
  "modules": {
    "PlanetPopulation": "AlbedoByRadius",
    "StarCatalog": "EXOCAT1",
    "OpticalSystem": "Nemati",
    "ZodiacalLight": "Stark",
    "BackgroundSources": "GalaxiesFaintStars",
    "PlanetPhysicalModel": "Forecaster",
    "Observatory": "WFIRSTObservatoryL2",
    "TimeKeeping": " ",
    "PostProcessing": " ",
    "Completeness": "BrownCompleteness",
    "TargetList": " ",
    "SimulatedUniverse": "SAG13Universe",
    "SurveySimulation": "tieredScheduler",
    "SurveyEnsemble_local": " ",
    "SurveyEnsemble": "EXOSIMS_local.IPClusterEnsembleJPL"
  },
   "completeness_specs":{
     "modules":{
       "PlanetPopulation": "EarthTwinHabZone1", 
       "PlanetPhysicalModel": " "
   }
  }
}

**Comment by dgarrett622** [comment]
@walker-dula are the unchanging completeness values you get all zero? 

I used a different set of fits files for the starlight suppression system dictionary in the json script since I don't have access to the fits files you are using. Based on the inner and outer working angles listed in the script Rhonda provided, EarthTwinHabZone1 planets could fall in this range. When I calculated the dMag at the intTimes you are looking at, I got a maximum value of ~21.5 at the largest integration time in the intTimes range (based on my fits files, your mileage may vary). If you look at the completeness "bird-plot" below, the values you integrate over are zero up until a dMag of ~22. 

Could you check the values used for smin, smax, and dMag in BrownCompleteness.comp_per_intTime? If those values are the reason for the unchanging completeness values you are getting, this isn't a bug, completeness is just integrating over a bunch of zeros. If that's not the reason, could you send me the range of values you get?

![earthtwinbirdplot](https://user-images.githubusercontent.com/19575707/37160478-4cc4b406-22be-11e8-9189-fe63fbf4d877.png)

**Comment by walker-dula** [comment]
Okay so here is what I am seeing. dMag as calculated by comps_input_reshape is always returning a value of -inf for all intTimes and sInds.

**Comment by dgarrett622** [comment]
dMag is calculated in `Nemati.calc_dMag_per_intTime` as:

`dMag = -2.5*np.log10((SNR*np.sqrt(C_b/intTimes + C_sp**2)/(C_F0*10.0**(-0.4*mV)*core_thruput*inst['PCeff'])).decompose().value)`

The only way for this to evaluate to `-inf` for all `intTimes` and `sInds` is if the following evaluates to inf:

`(SNR*np.sqrt(C_b/intTimes + C_sp**2)/(C_F0*10.0**(-0.4*mV)*core_thruput*inst['PCeff']))`

Based on the input json script Rhonda provided and some of the calculations in your code, I think the following terms are finite: `SNR`, `intTimes`, `C_F0`, `mV`, `inst['PCeff']`. The `core_thruput` term is a function of the fits files provided by the input json script. I don't have access to the fits files you are using, but the code doesn't throw a divide by zero error, so I think this term is bounded and nonzero. The only way the `C_b` and `C_sp` terms would not be finite is if there is something wrong with the optical system fits files or `fZ` or `fEZ` evaluated to `inf`.

Can you check that all the values going into `dMag` from above in `Nemati.calc_dMag_per_intTime` are finite and positive?

**Comment by walker-dula** [comment]
fZ and fEZ are not infinite, they are both on the order of 1e-10.

**Comment by rhondamorgan** [comment]
Here are the coronagraph files.
Rhonda

**Comment by dgarrett622** [comment]
The function calling comp_per_intTime from SurveySimulation has been updated to reflect changes elsewhere. This issue has been resolved.
