### ISSUE TITLE
SimulatedUniverse revise_planets_list() tries to access the size of None-initialized 'Min' attribute

### ISSUE THREAD

**Issue by neilzim** [dsavransky/EXOSIMS#139]
The default 'None' value of the 'Min' SimulatedUniverse attribute is causing trouble when I try to filter a planet list. Here is a trivial example to demonstrate:

```python
sim = EXOSIMS.MissionSim.MissionSim('sampleScript_coron.json')
sim.SimulatedUniverse.gen_physical_properties()
sim.SimulatedUniverse.init_systems()

jovian_pind = np.where( sim.SimulatedUniverse.Rp > 4*u.R_earth )[0]
sim.SimulatedUniverse.revise_planets_list( jovian_pind )
```

that results in the following error trace:

```
...EXOSIMS/EXOSIMS/Prototypes/SimulatedUniverse.py", line 468, in revise_planets_list
    if getattr(self, att).size != 0:

AttributeError: 'NoneType' object has no attribute 'size'
```

I went through the attributes and found it was due to the way 'Min' had been intialized:

```python
getattr(sim.SimulatedUniverse, 'Min').size
```
```
Traceback (most recent call last):

  File "<ipython-input-3-6f52dad4315d>", line 1, in <module>
    getattr(sim.SimulatedUniverse, 'Min').size

AttributeError: 'NoneType' object has no attribute 'size'
```

**Comment by neilzim** [comment]
Thanks for fixing this!

**Comment by dsavransky** [comment]
One additional comment:  it should not be necessary for you to manually call gen_physical_properties() and init_systems() (unless you have a specific reason to do so).   These are called at instantiation.  You can use those if you are trying to generate a new batch of planets, but then you should also probably pass the spec dict back into gen_physical_properties.  See reset_sim in SurveySimulation for an example.

**Comment by neilzim** [comment]
Good to know. I got in the habit of doing that because I have been filtering the target star list with brightness and distance cutoffs, and then looping through planet realizations applied to the shortened star list. Now that I read it, it looks likes reset_sim() will be a cleaner way to accomplish the same.
