### ISSUE TITLE
Planet non-detections being lost in divide-by-zero errors

### ISSUE THREAD

**Issue by mb2448** [dsavransky/EXOSIMS#15]
We occasionally get these warnings (not crashes) while running the EXOSIMS code, in this case for `MissionSim: Seed is:  507872323`.  I have attached the JSON file we used at the end.

```
EXOSIMS/Prototypes/SurveySimulation.py:505: RuntimeWarning: invalid value encountered in divide
  s,n = self.calc_signal_noise(sInd, pInds[obs], dt, mode)
```
This occurred with stars of index 153 and 319, which did not have obvious errors in magnitude or anything like that.

In SurveySimulation, the photon count rates returned are all zeros, so the divide calculates 0/0 which is obviously wrong.  _The planets are all closer than the inner working angle, so they should get flagged as "-1" in the detection criteria, but they go missing in the DRM instead, being empty._

As a separate suggestion, if the planets are within the inner working angle, it might save some time to have a short circuit in the code so that it doesn't compute count rates/etc which could save a bit of time.

JSON:
```

{
  "missionLife": 2.0,
  "missionPortion": 0.5,
  "ohTime": 0.1,
  "keepStarCatalog": true,
  "minComp": 0.1,
  "pupilDiam": 4,
  "obscurFac": 0,
  "dMagLim": 26,
  "telescopeKeepout": 60,
  "attenuation": 0.65,
  "intCutoff": 100.0,
  "settlingTime": 0.0, 
  "ppFact": 0.1,
  "prange":[0.2, 0.2],
  "erange":[0, 0.01],
  "eta": 0.1,
  "arange":[0.75, 1.77],
  "Rprange":[1.0, 1.0],
  "Mprange":[1, 1],
  "scaleOrbits": true,
  "constrainOrbits": true,
  "scienceInstruments": [
    {
      "name": "imagingEMCCD",
      "focal": 120,
      "pitch": 5e-6,
      "QE": 0.999,
      "idark": 0.0,
      "CIC": 0,
      "sread": 0.0,
      "ENF": 1,
      "texp": 1000
    },
    {
      "name": "spectroEMCCD",
      "focal": 120,
      "pitch": 5e-6,
      "QE": 0.999,
      "idark": 0.0,
      "CIC": 0,
      "sread": 0.0,
      "ENF": 1,
      "texp": 1000,
      "Rs": 50
    }
  ],
  "starlightSuppressionSystems": [
    {
      "name": "HLC550",
      "lam": 550,
      "IWA": 0.057,
      "OWA": 2.127,
      "ohTime": 0.1,
      "throughput": 0.2,
      "BW": 0.10,
      "occ_trans": 1.0,
      "core_thruput": 0.69, 
      "core_contrast": 1.7880e-10
    },
        {
      "name": "HLC1000",
      "lam": 1000,
      "BW": 0.1,
      "IWA": 0.1031,
      "OWA": 3.868,
      "ohTime": 0.2,
      "occ_trans": 1.0,
      "core_thruput": 0.69, 
      "core_contrast": 1.7880e-10
    }
  ],
      "observingModes": [
    {
      "instName": "imagingEMCCD",
      "systName": "HLC550",
      "detection": 1,
      "SNR": 7
    },
    {
      "instName": "spectroEMCCD",
      "systName": "HLC1000",
      "SNR": 5
    }
  ],
  "modules": {
    "PlanetPopulation": "EarthTwinHabZone1",
    "StarCatalog": "EXOCAT1",
    "OpticalSystem": "KasdinBraems",
    "ZodiacalLight": "Stark",
    "BackgroundSources": "GalaxiesFaintStars",
    "PlanetPhysicalModel": " ",
    "Observatory": "WFIRSTObservatoryL2",
    "TimeKeeping": " ",
    "PostProcessing": " ",
    "Completeness": "BrownCompleteness",
    "TargetList": " ",
    "SimulatedUniverse": " ",
    "SurveySimulation": " ",
    "SurveyEnsemble": " "
  }
}


```

**Comment by ChrisDelaX** [comment]
Thanks. The RuntimeError warning was a known issue, that I fixed this week.
Please check my last push on the Github. It's a bugfix containing:
- Runtime errors: divide-by-zero errors avoided in OpticalSystem and
SurveySimulation modules
- BrownCompleteness: updates array was disabled because causing an error in
some cases, and is now fixed and used again

Planets withing the IWA at a certain time might move in the observable
region later during the mission. A possible upgrade would be filter out
these which will never get in the IWA-OWA region during the whole mission.
I will see how to implement this in the preliminary filtering.

2017-02-02 19:13 GMT-05:00 mb2448 <notifications@github.com>:

**Comment by dsavransky** [comment]
@mb2448 can you confirm that the current version does not produce this behavior for you?

**Comment by mb2448** [comment]
The current version does not produce that behavior.
