### ISSUE TITLE
add stellar diameter to coronagraph performance

### ISSUE THREAD

**Issue by rhondamorgan** [dsavransky/EXOSIMS#163]
In the standard output file format as defined by Chris Stark with concurrence from John Krist, the stellar intensity map (used to calculate speckle leakage) is a stack of PSFs a function of x,y, and stellar angular diameter.

http://www.starkspace.com/yield_standards.pdf

While stars ~ 1mas are not much of an issue for WFIRST or even HabEx, they are a concern for LUVOIR, particularly with the APLC coronagraph.

Note that Chris' standard accept 2D PSF maps for inputs.  I reduce these maps in matlab to be able to provide a radial average curve .fits file to EXOSIMS.

**Comment by rhondamorgan** [comment]
This enhancement will greatly serve the decadal studies final reports, whose first draft is due December 15. Let's create a strategy for implementing this.

**Comment by deanthedream** [comment]
In our nominal operating mode, we would not change the cb_cp_csp prototype function for this.

The proper approach is to create a new OpticalSystem module "stellarDiam" which loads in "nemati" and you overload the cb_cp_csp function with the calculation as seen in the starkspace link you provided. 

The sticky bit of implementing this is the stellar diameter parameter bit (which we would have to take from a Star Catalog). We have to know the stellar diameter or have enough information to calculate it from ALL stars (where some stars may not have this information). I think by default we would assume the star is 0mas. I have never had to interface with the Star Catalog before and only recall Christian's complaints.

**Comment by dsavransky** [comment]
I think that we should consider a prototype update to be able to handle 3D PSF inputs.

In terms of calculating the stellar diameter - we can use the recently updated Mamjek table to interpolate these as we do with missing target info.  There certainly aren't any radii/diameters in EXOCAT or our other standard catalogs.

**Comment by deanthedream** [comment]
It at least appears the EXOCAT1.py catalog has the field for stelllar radii which I converted to stellar diameter. I added this to branch ramboRainbow.
