### ISSUE TITLE
de432s.bsp missing from install requirements/install

### ISSUE THREAD

**Issue by mb2448** [dsavransky/EXOSIMS#17]
The sample code 

```
import EXOSIMS,os.path
scriptfile = os.path.join(EXOSIMS.__path__[0],'Scripts','sampleScript_coron.json')
import EXOSIMS.MissionSim
sim = EXOSIMS.MissionSim.MissionSim(scriptfile)
```

Crashes with the following error:

`IOError: [Errno 2] No such file or directory: '/Users/mbottom/Desktop/Other_projects/EXOSIMS/code/EXOSIMS/Observatory/de432s.bsp'
`

I was able to download the file from this legitimate looking website:
https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/

And then the problem went away after I put it in the above directory /EXOSIMS/Observatory/.

**Comment by dsavransky** [comment]
Hi, sorry for the confusion.  We have this documented at https://rawgit.com/dsavransky/EXOSIMS/master/documentation/html/install.html - can you tell me which install document you were looking at?  Thanks.

**Comment by mb2448** [comment]
I was looking at the one you sent--the install document specifies de430.bsp; the actual file that is required is de432s.bsp.

**Comment by dsavransky** [comment]
You're right - sorry about that.  I've updated the install documentation.

**Comment by mb2448** [comment]
Just a note, it's still saying the wrong file.  It should be de432s.bsp,
not de432.bsp.
