### ISSUE TITLE
Update needed to Mamajek table

### ISSUE THREAD

**Issue by dsavransky** [dsavransky/EXOSIMS#176]
The table at:
 http://www.pas.rochester.edu/~emamajek/EEM_dwarf_UBVIJHK_colors_Teff.txt
has been updated to version 2018.08.02, making EXOSIMS's internal copy out of date.  This needs to be updated to match.

**Comment by dsavransky** [comment]
@dgarrett622 I'm not seeing this anywhere in master.  Do you still have a pull pending that will merge this in?

**Comment by dgarrett622** [comment]
I removed the commit because it didn't work. I'm not sure why the issue remained closed. I don't have anything right now that updates the table.

**Comment by dsavransky** [comment]
New plan: offload this functionality to new package MeanStars.
