### ISSUE TITLE
SLSQP Coin Branch Cut solver status unknown

### ISSUE THREAD

**Issue by deanthedream** [dsavransky/EXOSIMS#178]
Running HabEx on unconstrained star set with SLSQP

Coin branch cut terminates with unknown solver status....

Terminal Output
`/opt/local/lib/python2.7/site-packages/numpy/lib/function_base.py:2048: RuntimeWarning: invalid value encountered in integral (vectorized)
  outputs = ufunc(*inputs)
/home/drk94/Documents/exosims/EXOSIMS/EXOSIMS/Completeness/BrownCompleteness.py:496: RuntimeWarning: invalid value encountered in less
  comp[comp<1e-6] = 0.
[15:26:17] src/linear_solver/cbc_interface.cc:399: Unknown solver status! Secondary status: 0
Aborted
[drk94@atuin run]$ `

**Comment by dsavransky** [comment]
@deanthedream ping
