### ISSUE TITLE
Detection Time Allocation Assertion Fails During Ensembles

### ISSUE THREAD

**Issue by walker-dula** [dsavransky/EXOSIMS#193]
**Describe the bug**
On line 1174 of the SurveySimulation module, there is an assertion made that the total detection time  must be successfully allocated. This assertion error is triggered approximately 1% of the time during ensemble runs.
```
success = TK.allocate_time(intTime + extraTime + Obs.settlingTime + mode['syst']['ohTime'], True)#allocates time
assert success == True, "The Observation Detection Time to be Allocated %f was unable to be allocated"%(intTime + extraTime + Obs.settlingTime + mode['syst']['ohTime']).value
```

**To Reproduce**
cd /proj/exep/rhonda/Sandbox/HabEx

export PYTHONPATH=/proj/exep/rhonda/exosims_1.4Walker/EXOSIMS:$(pwd)/Local

python Local/ipcluster_ensemble_jpl_driver.py --standalone --seed 611229025 --outpath /tmp/junk --outopts drm:pkl,spc:spc Scripts/HabEx_4m_TSDDold_top200DD_promoteHZ_X_20181204.exp/s_c1=0.54_c2=0.24_c3=0.14.json 1

**Expected behavior**
The TS_DDold scheduler is not using refineOcculterSlews() to calculate the detection integration time. It's unclear to me if refineOcculterSlews() completely ensures that this assertion is never triggered or not. However, I do not think exiting the sim if this assertion is thrown is the best option here. Truncating the integration time and continuing to run the simulation until completion while throwing out a warning seems more flexible.

**JSON script:**
HabEx_4m_TSDDold_top200DD_promoteHZ_X_20181204.json

**EXOSIMS version:**
v1.4

**Comment by deanthedream** [comment]
Dmitry,

At the end of choose_next_target, we use:
`            #Check if exoplanetObsTime would be exceeded
            OS = self.OpticalSystem
            Comp = self.Completeness
            TL = self.TargetList
            Obs = self.Observatory
            TK = self.TimeKeeping
            allModes = OS.observingModes
            mode = filter(lambda mode: mode['detectionMode'] == True, allModes)[0]
            maxIntTimeOBendTime, maxIntTimeExoplanetObsTime, maxIntTimeMissionLife = TK.get_ObsDetectionMaxIntTime(Obs, mode)
            maxIntTime = min(maxIntTimeOBendTime, maxIntTimeExoplanetObsTime, maxIntTimeMissionLife)#Maximum intTime allowed
            intTimes2 = self.calc_targ_intTime(sInd, TK.currentTimeAbs.copy(), mode)
            if intTimes2 > maxIntTime: # check if max allowed integration time would be exceeded
                self.vprint('max allowed integration time would be exceeded')
                sInd = None
                waitTime = 1.*u.d`
To handle the issue where choose_next_target would like to allocate more time than is allowed.
We cannot simply truncate the integration time because we simultaneously allocate integration time + overheat + settling time. You can see the issue if the integration time to be allocated is less than the ohtime + settling time.
Do we want to change the default logic here @dsavransky ?


Walker,
Are you implementing the aforementioned logic? Also I don't have access to your (script or code?) to properly check and debug.

**Comment by walker-dula** [comment]
Is this code in the master branch of EXOSIMS? I don't see it in SurveySimulation. This is what i am seeing for choose_next_target():

```
    def choose_next_target(self, old_sInd, sInds, slewTimes, intTimes):
        """Helper method for method next_target to simplify alternative implementations.
        
        Given a subset of targets (pre-filtered by method next_target or some 
        other means), select the best next one. The prototype uses completeness 
        as the sole heuristic.
        
        Args:
            old_sInd (integer):
                Index of the previous target star
            sInds (integer array):
                Indices of available targets
            slewTimes (astropy quantity array):
                slew times to all stars (must be indexed by sInds)
            intTimes (astropy Quantity array):
                Integration times for detection in units of day
        
        Returns:
            sInd (integer):
                Index of next target star
            waitTime (astropy Quantity):
                some strategic amount of time to wait in case an occulter slew is desired (default is None)
        
        """
        
        Comp = self.Completeness
        TL = self.TargetList
        TK = self.TimeKeeping
        
        # cast sInds to array
        sInds = np.array(sInds, ndmin=1, copy=False)
        # calculate dt since previous observation
        dt = TK.currentTimeNorm.copy() + slewTimes[sInds] - self.lastObsTimes[sInds]
        # get dynamic completeness values
        comps = Comp.completeness_update(TL, sInds, self.starVisits[sInds], dt)
        # choose target with maximum completeness
        sInd = np.random.choice(sInds[comps == max(comps)])

        return sInd, slewTimes[sInd] #if coronagraph or first sInd, waitTime will be 0 days
```

**Comment by dsavransky** [comment]
@walker-dula Can you confirm that the last merge fixed this issue?

**Comment by deanthedream** [comment]
@Dmitry, This is the logic I implement in SLSQP to avoid this termination
error.
I simply implemented it in the prototype module.

I believe Walker's error only occured once for every 1000 sims or
so(@walker correct me if I am wrong)

I think this issue should be closed

Regards,

Dean Keithly

PhD Student - Cornell University
M.E. Systems Engineering - Cornell University
B.S. Mechanical Engineering - Michigan Technological University
Phone: 248-421-3157
email:drk94@cornell.edu
