### ISSUE TITLE
IWA and Loading from outspec

### ISSUE THREAD

**Issue by deanthedream** [dsavransky/EXOSIMS#223]
A simulation specifying an IWA of 0.15 in the input json script can write IWA=0.289... to outspec.json. This happens because of the nearest star distance and re-adjustment of the IWA to be the smallest possible planet generated (I think its something like 0.289 arcsec = (0.1 AU + eccen correction)*2.34pc, but could just be based off sma)

While this doesn't effect current script, it is possible that this results in some kind of feedback look and it is further modified under some conditions. (Pretty sure there is code that takes (IWA+OWA)/2 for some WA calculations, think it is dependent on another input parameter)

This bug primarily effects plotting utilities and use cases where the user loads from outspec.

**Comment by dsavransky** [comment]
Where exactly is the IWA being modified?  I don't think anything should overwrite instrumental parameters based off of target list/population values.  This is something we should fix.

**Comment by dsavransky** [comment]
Issues does not appear to be present in current version.
