### ISSUE TITLE
Difficulty solving for dMag(intTimes) in Nemati_2019 (non-analytic)

### ISSUE THREAD

**Issue by jrenrut** [dsavransky/EXOSIMS#225]
`calc_dMag_per_intTime` and `ddMagdt` from the `Nemati` module work with the prototype `Cp_Cb_Csp`, they have analytical solutions. The `Cp_Cb_Csp` method in `Nemati_2019` has additional dependencies on `dMag`. Solving everything out gives:

![tSNR](https://user-images.githubusercontent.com/42989238/58065419-a7d88e00-7b53-11e9-9c7f-122ce0d06cc1.jpg)

I've recreated this as a lambda function and tried using `scipy.optimize.fsolve` to get a numerical solution. The result is:

`RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)`

and the output `dMag` is the same as the initial guess `x0` from `fsolve`.

A working `calc_dMag_per_intTime` method should work circularly: it should return a dMag which, as an input to `calc_intTime`, would produce the same `intTime` originally used in `calc_dMag_per_intTime`.

Without a solution for `dMag`, the `ddMagdt` method will not work.

Using 'sampleScript_coron.json', EXOSIMS master, jrenrut fork.

**Comment by dsavransky** [comment]
Fixed by #285
