### ISSUE TITLE
move fEZ to a star attribute

### ISSUE THREAD

**Issue by rhondamorgan** [dsavransky/EXOSIMS#240]
The Mennesson exozodi model assigns a different fEZ to each planet, but the integration time is selected by star. this causes poor integration times for some planets resulting in degraded yields.

fEZ should be assigned to the star, so that one integration time for all the planets around that star can be calculated.

**Comment by deanthedream** [comment]
Discussion on proper implementation is required

**Comment by dsavransky** [comment]
@deanthedream It seems like this is very analogous to the changes you're proposing for the mutual system inclination.  Perhaps the two updates can be folded together?
