### ISSUE TITLE
Python 3.6 dependency issue when instantiating MissionSimulation object

### ISSUE THREAD

**Issue by berlinchen7** [dsavransky/EXOSIMS#250]
Instantiating `MissionSimulation` object crashes when running Python 3.6. Traceback showed that the error originated in line 24 of `EXOSIMS/Prototype/TargetList.py`, where the program was unable to import `urllib3`. `pip install urllib3` fixed the problem, but it seems that `setup.py` should have taken care of this.

To see that `urllib3` is indeed not preinstalled in Python 3.6:

```bash
$ conda create -n mytestenv python=3.6
$ conda activate mytestenv
$ python
>> import urllib3
```

P.S. The package `pkg_resources` is actually pre-installed in Python 3.6 but just not imported in `Prototype/TargetList.py`, which is an issue only in the bijan2019 branch and not the master.

**Comment by CoreySpohn** [comment]
urllib3 has been added to the setup.py and requirements files on bijan2019 and the pkg_resources import is fixed. It'll all be updated when bijan2019 is pulled. I could also make a pull request with just the urllib fix.

**Comment by CoreySpohn** [comment]
#251
