### ISSUE TITLE
OpticalSystem asserts values less than one which should be allowed greater than one

### ISSUE THREAD

**Issue by wbalmer** [dsavransky/EXOSIMS#253]
**Describe the bug**
Parameters like core_area can in reality be greater than one, but are not allowed by an assertion on lines 566-568 within the get_coro_param method within the OpticalSystem prototype.

**To Reproduce**
Introduce a core_area (or other parameter) that is larger than one within a script, and ensure the script's starlightSuppressionSystems' "occulter" parameter is false.  

**Expected behavior**
Parameters like core_area should be allowed to be greater than one, and should not provoke an error. 

**EXOSIMS version:**
 - master: 0c46945
 - bijan2019: 58e679f
 - balmer2020: c213616

**Additional context**
Quick fix on balmer2020: acc3909

**Comment by dsavransky** [comment]
fold into photometry update
