### ISSUE TITLE
contrast_floor parameter causes index error in OpticalSystem Cp_Cb_Csp

### ISSUE THREAD

**Issue by wbalmer** [dsavransky/EXOSIMS#254]
**Describe the bug**
If a script includes the "contrast_floor" parameter, the if statement beginning on line 644 leads to an index error on lines 653-654 for reasonable contrast_floor values. 

`core_intensity[np.where(contrast < contrast_floor)]=contrast_floor* \
                core_thruput[np.where(contrast < contrast_floor)]`

**To Reproduce**
Set "contrast_floor" to a value such as 1e-7 within the starlightSuppressionSystems and begin a simulation. 

**Expected behavior**

**JSON script:**
If applicable, add the script you are using.

**EXOSIMS version:**
 - master: 0c46945
 - bijan2019: 58e679f
 - balmer2020: c213616

**Comment by dsavransky** [comment]
Fold into photometry update.
