### ISSUE TITLE
Create a way to compare the input json and outspec to see differences

### ISSUE THREAD

**Issue by CoreySpohn** [dsavransky/EXOSIMS#256]
**Is your feature request related to a problem? Please describe.**
EXOSIMS fills in values for parameters that are not given by the input json file. This behavior is expected but it can be useful to see what values have been filled in to make sure that the input file is behaving as expected.

**Describe the solution you'd like**
A function that prints out the differences between the input and the outspec generated by the simulation. I assume that this would be a util function.

**Additional context**
The idea for this came from looking at the values that Nemati_2019 tries to load from the input using try-except statements.

**Comment by deanthedream** [comment]
I have something like this somewhere... Possibly not committed because it isn't completed

**Comment by dsavransky** [comment]
Mainlined in MissionSim in 3.0.0.
