### ISSUE TITLE
add Lsatmax parameter

### ISSUE THREAD

**Issue by rhondamorgan** [dsavransky/EXOSIMS#270]
This phrase occurs in Prototypes/OpticalSystem.py and Prototypes/SurveySimulation.py
          for i,Lstar in enumerate(TL.L):
-            if (Lstar < 3.85) and (Lstar > 0. ):
                 dMag[i] = self.dMag0 + 2.5 * np.log10(Lstar)
             else:
                 dMag[i] = self.dMag0

The hardcoded number 3.85 lends itself well to being turned into a parameter for the json file.  I suggest LstarMax as the parameter name.
The number changes with the the noise floor of the instrument, which is calculated and verbosely displayed at runtime:
Limiting delta magnitude for mode syst: APLC inst: imagingUV475_EMCCD is 26.5800579469
Limiting delta magnitude for mode syst: APLC inst: imagingVis550_EMCCD is 27.5749079686
Limiting delta magnitude for mode syst: APLC inst: spectral910_EMCCD is 27.9402280578

I calculate LstarMax to be ~5% (or some margin) < 10^(limiting deta mag above - (dMagLim - dMagLim_offset))/2.5

dMagLim and dMagLim_offset are input variables, and LstarMax is dependent on them.
For earth imaging architectures, I typically use
  "dMagLim": 26.5,
  "dMagLim_offset": 1.5,
so that the completeness will be calculated to 26.5, and then subtracting dMagLim_offset of 1.5 will set the dMag for integration time calculations for earth twin at quadrature (dMag = 25).
For LUVOIR, I typically use 6.85 for the suggested LstarMax parameter.
Fro HabEx coronagraph, 3.85, for habEx occulter, 6.85.

The default value of LstarMax will need to be added to both OpticalSystem and SurveySimulation.  They could get out of sync in future modifications, but we will live with this for now, because users like me will override with the json parameter file value, and we will set the default to be useful for WFIRST, since most the defaults are for WFIRST and WFIRST users will not lilkely be aware of this parameter.

**Comment by dsavransky** [comment]
This issue is deprecated by TargetList updates and deprecation of dMagLim_offset.
