### ISSUE TITLE
TargetList prototype does not convert int to np array in F0 calculation method.

### ISSUE THREAD

**Issue by jkulik11** [dsavransky/EXOSIMS#274]
**Describe the bug**
TargetList prototype does not convert int to np array in F0 calculation method.

**To Reproduce**
Run Gabe's produce_skmap.py code from his scripts, while in the stationkeep branch. (I'm sure this bug is also in master, but am not sure exactly how to reproduce it there.)

**Additional context**
Copy the first line of starMag() method and make the first line of starF0() to fix.
"sInds = np.array(sInds, ndmin=1, copy=False)"

**Comment by dsavransky** [comment]
Folded into photometry update.
