### ISSUE TITLE
genOutSpec not recognizing git repository

### ISSUE THREAD

**Issue by dsavransky** [dsavransky/EXOSIMS#28]
Getting the "Not a valid Github or SVN revision." error when running from current git master branch.

**Comment by ChrisDelaX** [comment]
Can't reproduce this bug. I just tried:
    sim = EXOSIMS.MissionSim.MissionSim(scriptfile)
    sim.SurveySimulation.run_sim()
    sim.genOutSpec()
>> Github last commit b58f795df68445c62d0e22ffe976985c1f48356a
It's weird. Could you check once more, that you're synced with the master, and you're calling EXOSIMS from your GitHub repository?

**Comment by dsavransky** [comment]
Were you running from the repository dir or another random location?

**Comment by ChrisDelaX** [comment]
Okay, I changed repos and reproduced your result. I will fix this now.

2017-03-20 14:03 GMT-04:00 Dmitry Savransky <notifications@github.com>:

**Comment by ChrisDelaX** [comment]
I coded genOutSpec in the same way as everywhere else in EXOSIMS where we
need to get a path with respect to the module we're working in:
     path = os.path.split(inspect.getfile(self.__class__))[0]
We do the same thing in the following modules:
grep -irl "inspect.getfile(self.__class__)" ./ --include="*.py"
.//EXOSIMS/BackgroundSources/GalaxiesFaintStars.py
.//EXOSIMS/Completeness/BrownCompleteness.py
.//EXOSIMS/Completeness/GarrettCompleteness.py
.//EXOSIMS/MissionSim.py
.//EXOSIMS/Observatory/WFIRSTObservatoryL2.py
.//EXOSIMS/PlanetPhysicalModel/Forecaster.py
.//EXOSIMS/PlanetPhysicalModel/FortneyMarleyCahoyMix1.py
.//EXOSIMS/PlanetPopulation/KnownRVPlanets.py
.//EXOSIMS/Prototypes/Observatory.py
.//EXOSIMS/StarCatalog/EXOCAT1.py
.//EXOSIMS/StarCatalog/SIMBAD300Catalog.py
.//EXOSIMS/ZodiacalLight/Stark.py

Hence, the user needs to run EXOSIMS from the repository dir to make these
features work. I didn't find a way to get the absolute path of EXOSIMS
while being in a random location. I tried
     os.path.abspath(inspect.getfile(self.__class__))
but this produces
     '/...(random location).../EXOSIMS/MissionSim.pyc'


2017-03-20 14:15 GMT-04:00 Christian Delacroix <
christian.delacroix@gmail.com>:
