### ISSUE TITLE
fZQuads must be updated to handle multiple instruments

### ISSUE THREAD

**Issue by deanthedream** [dsavransky/EXOSIMS#289]
https://github.com/dsavransky/EXOSIMS/blob/48ed9cddb41b1dff14503052671d296dc2ded1be/EXOSIMS/Prototypes/ZodiacalLight.py#L364

**Comment by deanthedream** [comment]
Basically the small section of code before this and this section of code need to be updated to handle multiple instruments in the spec file.
Nobody used 2 instruments when this was first created.
Basically if fZQuads is calculated based on the keepout map of a coronagraph (which has smaller KO regions), then time will be advanced based on "Izod:fZmin" policies to the local zodiacal light within the substantially larger KO window of the starshade instrument.
fZQuads needs to be iterated over and computed separately for multiple different instruments.
It is also important to take the integration time into account when advancing time (you need to advance to a time before the target star exits keepout. this is accounted for in the coronagraph only scenarios of SLSQP, there is some small potential it isnt since I only needed to advance to fZmin).

**Comment by dsavransky** [comment]
Implemented in v3.0.0.
