### ISSUE TITLE
Update to compute fZmin for all targets (remove sInds as input) and update hashname to incorporate mode into cachename

### ISSUE THREAD

**Issue by deanthedream** [dsavransky/EXOSIMS#292]
https://github.com/dsavransky/EXOSIMS/blob/7a22a8a2d084490b05987839431e00e2a0483ae7/EXOSIMS/Prototypes/ZodiacalLight.py#L280

**Comment by dsavransky** [comment]
@ggenszler I believe this has been/will be covered in your current updates.  Please tag this issue on next relevant commit or close if it is already covered.

**Comment by dsavransky** [comment]
Closed by #327
