### ISSUE TITLE
version bump request

### ISSUE THREAD

**Issue by douglase** [dsavransky/EXOSIMS#296]
the  current release is somewhat stale and in particular doesn't include the HIPfromSimbad function, bumping the release would make it easier to deploy examples (e.g. the [Binder](https://arxiv.org/abs/2112.12804) that reproduces the figures in  https://arxiv.org/abs/2112.12804 which rely on the HIPfromSimbad function).

**Comment by dsavransky** [comment]
@douglase Sorry for the delay.  Major version update is now live.
