### ISSUE TITLE
in Prototype OpticalSystem calc_maxintTime doesn't check for OWA < 2*IWA

### ISSUE THREAD

**Issue by dsavransky** [dsavransky/EXOSIMS#31]
Currently WA is set to 2.*self.IWA, but this can produce a silent (non-terminating) error when OWA < 2*IWA.  Should be an explicit check for this condition, in which case WA should be set to (IWA+OWA)/2.

**Comment by ChrisDelaX** [comment]
I will set the default WA for filtering to (IWA+OWA)/2 unless OWA is inf,
then WAfilter = 2*IWA

2017-04-06 15:57 GMT+02:00 Dmitry Savransky <notifications@github.com>:
