### ISSUE TITLE
linearJScheduler slew distance by star index is incorrect

### ISSUE THREAD

**Issue by walker-dula** [dsavransky/EXOSIMS#32]
In the linearJScheduler module, if the OpticalSystem used has an occulter, the weighting by slew distance to neighboring target stars is incorrect. Cutting out all other weighting factors, each next target star should be the one closest to the current star; however, the traversal instead looks like so (where the stars in red are those that are visited over a 1-year period):

![sky_targets_order](https://cloud.githubusercontent.com/assets/27707096/25106412/2bea00f0-237e-11e7-8981-8a4b18bdef63.png)

From narrowing down the source of the error, I believe there is an indexing problem where the correct star weights are being attributed to the incorrect star index.
 
The source of the problem should be in one of these two code blocks:
```
if OS.haveOcculter:
    combs = np.array([np.array(x) for x in itertools.combinations(range(nStars),2)])
    r_ts = Obs.starprop(TL, sInds, TK.currentTimeAbs)
    u_ts = (r_ts.value.T/np.linalg.norm(r_ts,axis=1)).T # good to here
    angdists = np.arccos(np.clip(np.dot(u_ts,u_ts.T)[combs[:,0],combs[:,1]],-1,1))
    A[np.tril(np.ones((nStars,nStars),dtype=bool),-1)] = angdists
    A = self.coeffs[0]*(A+A.T)/np.pi
```

```
lc = nStars-1
step1 = np.tile(A[sInds==old_sInd,:],(lc,1)).flatten('F')
step2 = A[np.array(np.ones((nStars,nStars)) - np.eye(nStars),dtype=bool)]
tmp = np.argmin(step1+step2)
sInd = sInds[int(np.ceil(tmp/float(lc)))]
```

Note:
I decided to rewrite some of the old code to create a depth=1 search to narrow down the source of the error. I replaced the above code blocks with the following:

```
slews = np.zeros(nStars)
r_curr = Obs.starprop(TL, old_sInd, TK.currentTimeAbs)
u_curr = (r_curr.value/np.linalg.norm(r_curr,axis=1))

r_seq = Obs.starprop(TL, sInds, TK.currentTimeAbs)
u_seq = (r_seq.value.T/np.linalg.norm(r_seq,axis=1)).T
angdists = np.arccos(np.dot(u_seq,u_curr.T))
slews[np.ones((nStars),dtype=bool)] = angdists
slews = slews/np.pi
slews = np.where(slews==0,np.Inf,slews)
```

```
sInd = sInds[np.argmin(slews)]
```

This produced a result that seemed to make more sense, and led me to believe that the problem is caused by an error when the star weights are used to choose the next target by sInd.The results of the above code can be seen below:

![skytest](https://cloud.githubusercontent.com/assets/27707096/25106726/f0bfa0f0-237f-11e7-9110-e9ed9daf5faf.png)

**Comment by walker-dula** [comment]
Update:
The following changes to the code seem to have fixed the original problem while keeping the same general code structure:

```
if OS.haveOcculter:
    r_ts = Obs.starprop(TL, sInds, TK.currentTimeAbs)
    u_ts = (r_ts.value.T/np.linalg.norm(r_ts,axis=1)).T
    angdists = np.arccos(np.clip(np.dot(u_ts,u_ts.T),-1,1))
    A[np.ones((nStars),dtype=bool)] = angdists
    A = self.coeffs[0]*(A)/np.pi
```

```
step1 = np.tile(A[sInds==old_sInd,:],(nStars,1)).flatten('F')
step2 = A[np.array(np.ones((nStars,nStars)),dtype=bool)]
tmp = np.argmin(step1+step2)
sInd = sInds[int(np.floor(tmp/float(nStars)))]
```

**Comment by dsavransky** [comment]
Excellent, thank you.  Can you submit a pull request?

**Comment by ChrisDelaX** [comment]
@deanthedream  merged the pull request. Closing this issue.
