### ISSUE TITLE
Fix generation of longitude of ascending node.

### ISSUE THREAD

**Issue by CoreySpohn** [dsavransky/EXOSIMS#324]
**Describe the bug**
Omega is generated uniformly which puts orbits on a sphere instead of a plane since the inclinations are not generated to be near zero.

**To Reproduce**
Generate any planetary system that is supposed to have a common system inclination.

**Expected behavior**
When commonSystemInclination is True there should be a common orbital planet.

**JSON script:**
N/A

**EXOSIMS version:**
 - master

**Additional context**
N/A

**Comment by dsavransky** [comment]
@CoreySpohn This is closed by #360,  right?

**Comment by CoreySpohn** [comment]
Yep
