### ISSUE TITLE
Rounding dMag array in observation_detection in the case of FA

### ISSUE THREAD

**Issue by 96armen** [dsavransky/EXOSIMS#368]
**Describe the bug**
A bug in the SurveySimulation Prototype for the case of an FA in observation_detection. When logging, the dMag array is attempted to be rounded using the 'round' method.

**Expected behavior**
Each item in the dMag array should be rounded to first decimal place.

**EXOSIMS version:**
 - 3.2.0, inttimesdebug branch

**Additional context**
Problem can be solved by simply changing 'round' to 'np.round'

**Comment by dsavransky** [comment]
Closed by #385
