### ISSUE TITLE
Core_platescale rescaling in OpticalSystem Prototype

### ISSUE THREAD

**Issue by 96armen** [dsavransky/EXOSIMS#386]
**Describe the bug**
In the OpticalSystem Prototype, in the Cp_Cb_Csp_helper method, the core_platescale is rescaled by the ratio of detection/characterization mode lambda to coronagraph lambda: mode["lam"]/syst["lam"]. This is done after a variable "core_platescale" is set to syst["core_platescale"]. However, the syntax here essentially makes these two the same object, such that the syst["core_platescale"] is also being scaled even though it should be constant. Subsequent calls to Cp_Cb_Csp_helper will rescale core_platescale again such that over time it will be erroneously rescaled many times. This can lead to very small (or very large) core_platescale that will affect things like the core_intensity further down the line.

**To Reproduce**
Any generic simulation where mode["lam"] does not equal syst["lam"] will reproduce this.

**Expected behavior**
We expect the variable core_platescale to be rescaled by the ratio of mode["lam"]/syst["lam"] but that syst["core_platescale"] be immutable in this operation.

**EXOSIMS version:**
 - 3.3.0

**Additional context**
A suggested quick fix of this issue is to add 0.0 when setting core_platescale equal to syst["core_platescale"]. This will ensure that the two are separate objects so that scaling one does not affect the other.

**Comment by dsavransky** [comment]
Closed by #385
