### ISSUE TITLE
Outdated function calls no longer exist

### ISSUE THREAD

**Issue by walker-dula** [dsavransky/EXOSIMS#39]
Several modules now contain function calls that are now outdated and break on execution.

In Observatory.py, function distForces, line 691:

`r_targ = TL.starprop_equat(sInd, currentTime)[0F] - r_obs` should be changed to `r_targ = TL.starprop(sInd, currentTime)[0] - r_obs`

In linearJScheduler.py, line 83:

`r_ts = Obs.starprop(TL, sInds, TK.currentTimeAbs)` should be changed to `r_ts = TL.starprop(sInds, TK.currentTimeAbs)`

There may be other instances of these problem in modules that I have not run yet.

**Comment by ChrisDelaX** [comment]
Good catch. That's an easy fix, it should be TL.starprop
I checked this typo doesn't appear anywhere else and it doesn't:
```
dhcp-rhodes-647:gitexosims cdelacroix$ grep -ir "starprop_equat" ./ --include="*.py"
.//EXOSIMS/Prototypes/Observatory.py:        r_targ = TL.starprop_equat(sInd, currentTime)[0] - r_obs

```

**Comment by ChrisDelaX** [comment]
and also:
```
dhcp-rhodes-647:gitexosims cdelacroix$ grep -ir "Obs.starprop" ./ --include="*.py"
.//EXOSIMS/SurveySimulation/linearJScheduler.py:            r_ts = Obs.starprop(TL, sInds, TK.currentTimeAbs)
```
