### ISSUE TITLE
PlanetPhysicalModel looks for non-existent file

### ISSUE THREAD

**Issue by neilzim** [dsavransky/EXOSIMS#40]
I followed the quickstart instructions at https://github.com/dsavransky/EXOSIMS/blob/master/documentation/quickstart.rst, using the example script 'sampleScript_coron.json'

When I instantiate the MissionSim via
sim = EXOSIMS.MissionSim.MissionSim(scriptfile)

The PlanetPhysicalModel module has an error trying to locate a non-existent file, planetphysicalmodel/fitting_parameters.h5.

I pased my error trace below.

/Users/nzimmerm/WFIRST_tech/EXOSIMS/EXOSIMS/Prototypes/PlanetPopulation.py in __init__(self, arange, erange, Irange, Orange, wrange, prange, Rprange, Mprange, scaleOrbits, constrainOrbits, eta, **specs)
     99         # import PlanetPhysicalModel
    100         self.PlanetPhysicalModel = get_module(specs['modules']['PlanetPhysicalModel'],
--> 101                 'PlanetPhysicalModel')(**specs)
    102 
    103     def checkranges(self, var, name):

/Users/nzimmerm/WFIRST_tech/EXOSIMS/EXOSIMS/PlanetPhysicalModel/Forecaster.py in __init__(self, n_pop, **specs)
     30         filename = 'fitting_parameters.h5'
     31         parampath = os.path.join(classpath, filename)
---> 32         h5 = h5py.File(parampath, 'r')
     33         self.all_hyper = h5['hyper_posterior'][:]
     34         h5.close()

/Users/nzimmerm/anaconda3/envs/py27/lib/python2.7/site-packages/h5py/_hl/files.pyc in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    270 
    271                 fapl = make_fapl(driver, libver, **kwds)
--> 272                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    273 
    274                 if swmr_support:

/Users/nzimmerm/anaconda3/envs/py27/lib/python2.7/site-packages/h5py/_hl/files.pyc in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     90         if swmr and swmr_support:
     91             flags |= h5f.ACC_SWMR_READ
---> 92         fid = h5f.open(name, flags, fapl=fapl)
     93     elif mode == 'r+':
     94         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)()

h5py/h5f.pyx in h5py.h5f.open (/Users/ilan/minonda/conda-bld/work/h5py/h5f.c:1942)()

IOError: Unable to open file (Unable to open file: name = '/users/nzimmerm/wfirst_tech/exosims/exosims/planetphysicalmodel/fitting_parameters.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by dsavransky** [comment]
See the 'Optional Packages' section of the install docs:

https://cdn.rawgit.com/dsavransky/EXOSIMS/master/documentation/html/install.html#optional-packages
