### ISSUE TITLE
infinite OBduration writes to outspec as invalid value

### ISSUE THREAD

**Issue by dsavransky** [dsavransky/EXOSIMS#41]
OBduration, when left at default (Infinity) goes to outspec as Infinity, which is not a valid json value.  This should be handled in the same way as OWA.

**Comment by ChrisDelaX** [comment]
OWA infinite values also write as such to outspec.
```In [3]: OS._outspec['OWA']
Out[3]: inf

In [4]: OS._outspec['starlightSuppressionSystems'][0]['OWA']
Out[4]: inf ```

**Comment by ChrisDelaX** [comment]
@dsavransky I ran this test without errors:
```
In [12]: temp = sim.genOutSpec('temp.json')

In [13]: specs = json.loads(open('temp.json').read())

In [14]: specs['OWA']
Out[14]: inf

In [15]: specs['OBduration']
Out[15]: inf
```

**Comment by dsavransky** [comment]
okay - looking into the docs, it turns out that while inf/nan are strictly disallowed by json specification, the python json module is totally fine with them.  So, this is only an issue if we want a non-python json parser to be able to read these.  This seems like a super low-priority thing, so I'm going to mark this wontfix and close for now.
