### ISSUE TITLE
BrownCompleteness gen_updates array ValueError

### ISSUE THREAD

**Issue by rhondamorgan** [dsavransky/EXOSIMS#5]
I used scriptfile template_WFIRST_EarthTwinHabZone.json, but with OpticalSystem set to Nemati.
The MC completeness calculation was performed, then received an error upon Beginning completeness update.  here is the Traceback:

Monte Carlo completeness calculations finished
2D completeness array stored in u'EXOSIMS/Completeness/EarthTwinHabZone2.comp'
/Users/rhonda/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/units/quantity.py:822: RuntimeWarning: invalid value encountered in true_divide
  return super(Quantity, self).__truediv__(other)
EXOSIMS/Completeness/BrownCompleteness.py:106: RuntimeWarning: divide by zero encountered in log10
  dMag = dMag - 2.5*np.log10(targlist.L)
/Users/rhonda/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/lib/function_base.py:1769: RuntimeWarning: invalid value encountered in ? (vectorized)
  outputs = ufunc(*inputs)
Beginning completeness update calculations
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-af9af77f0f9d> in <module>()
----> 1 sim = EXOSIMS.MissionSim.MissionSim(scriptfile)

/Users/rhonda/exosims.2.0/EXOSIMS/EXOSIMS/MissionSim.pyc in __init__(self, scriptfile, **specs)
    107         self.modules = {}
    108         self.modules['SimulatedUniverse'] = get_module(specs['modules']\
--> 109                 ['SimulatedUniverse'],'SimulatedUniverse')(**specs)
    110         self.modules['Observatory'] = get_module(specs['modules']\
    111                 ['Observatory'],'Observatory')(**specs)

/Users/rhonda/exosims.2.0/EXOSIMS/EXOSIMS/Prototypes/SimulatedUniverse.pyc in __init__(self, eta, **specs)
     87 
     88         # import TargetList class
---> 89         self.TargetList = get_module(specs['modules']['TargetList'],'TargetList')(**specs)
     90 
     91         # bring inherited class objects to top level of Simulated Universe

/Users/rhonda/exosims.2.0/EXOSIMS/EXOSIMS/Prototypes/TargetList.pyc in __init__(self, keepStarCatalog, minComp, **specs)
    139 
    140         # generate any completeness update data needed
--> 141         self.Completeness.gen_update(self)
    142 
    143         # have target list, no need for catalog now

/Users/rhonda/exosims.2.0/EXOSIMS/EXOSIMS/Completeness/BrownCompleteness.pyc in gen_update(self, targlist)
    147             smax = (np.tan(targlist.OpticalSystem.OWA)*targlist.dist).to('AU')
    148         else:
--> 149             smax = np.array([np.max(self.PlanetPopulation.arange)*(1.+np.max(self.PlanetPopulation.erange))]*targlist.nStars)
    150         # fill dynamic completeness values
    151         for sInd in xrange(targlist.nStars):

ValueError: setting an array element with a sequence.

**Comment by dgarrett622** [comment]
BrownCompleteness.py has been updated and no longer has this issue.

**Comment by rhondamorgan** [comment]
Hi Daniel,
I pulled the most recent update and received an error that makes it look like EVPOC is empty.  I reported the bug on github.  Please investigate this as soon as possible as it is holding up end to end analysis I am trying to do for HabEx.
Thank you,
Rhonda

**Comment by dgarrett622** [comment]
Hi Rhonda,

The issue before was related to completeness update values, nothing was modified in the target_completeness method. This may be something new.

I used the scriptfile template_WFIRST_EarthTwinHabZone.json and did not see this issue.

Can you send me the scriptfile you used when you saw this issue?
Was a .comp file loaded or did BrownCompleteness perform Monte Carlo trials?

Thanks,

Daniel

**Comment by rhondamorgan** [comment]
Brown completeness performed the MC. I'll send you the script when I return from lunch.
Thank you,
Rhonda

Sent from my iPhone

On Jun 21, 2016, at 11:59 AM, Daniel Garrett <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Rhonda,

The issue before was related to completeness update values, nothing was modified in the target_completeness method. This may be something new.

I used the scriptfile template_WFIRST_EarthTwinHabZone.json and did not see this issue.

Can you send me the scriptfile you used when you saw this issue?
Was a .comp file loaded or did BrownCompleteness perform Monte Carlo trials?

Thanks,

Daniel

**Comment by rhondamorgan** [comment]
HI Daniel, here is my script.  I’d appreciate any insight you have as to why this error was triggered.
Thank you,
Rhonda

**Comment by dgarrett622** [comment]
It looks like the script didn't get attached.

**Comment by rhondamorgan** [comment]
Trying again with the attachment.  Let me know if the attachment doesn’t come through, maybe the mail filter doesn’t like .json.

**Comment by dgarrett622** [comment]
The mail filter must not like .json, I still don't see the attachment.

**Comment by rhondamorgan** [comment]
OK, trying it as .zip
