### ISSUE TITLE
test the random seed

### ISSUE THREAD

**Issue by ChrisDelaX** [dsavransky/EXOSIMS#59]

**Comment by ChrisDelaX** [comment]
Numpy random seed is created in MissionSim, and passed to SurveySimulation through the specs dictionary.
SurveySimulation can also generate a random seed if it is not in the specs dictionary.
The numpy.random.seed(self.seed) call is made in SurveySimulation.

**Comment by dsavransky** [comment]
This has been confirmed as working via a few different tests now.  Closing.
