### ISSUE TITLE
find a better way to include the radiation dosage in the Optical System

### ISSUE THREAD

**Issue by ChrisDelaX** [dsavransky/EXOSIMS#61]
As Bijan Nemati uses it, radiation dosage (radDos) should go from 0 (beginning of mission) to 1 (end of mission). Currently, radDos defaults to 0, and can be specified for each observingMode, e.g. radDos = 0.5 with detection mode, and 1 with characterization mode (cf. Bijan's values). This assumes most of the detections will occur at mid-term of the mission, and characterizations close to the end of the mission. In practice, radDos should not be fixed for each observingMode but rather a function of the mission currentTime.

**Comment by dsavransky** [comment]
In reality, the dosage should be linked to the actual time in space.  That is - the radDos should only be 1 at the end of the nominal mission duration (5 or 6 years for WFIRST, for example).  If you run a shorter sim (say for only 2.5 years) radDos shouldn't go above 0.5.

The best (most general) way to implement this would be to have the observatory include a method that kept track of cumulative radiation dose as a function of mission normalized time.  The optical system could then use this value however it wished.

**Comment by dsavransky** [comment]
This will be handled by the new OpticalSystem implementation porting the current Nemati spreadsheet.

**Comment by dsavransky** [comment]
This is going to be handled by new Nemati method, projected for 2.1.

**Comment by dsavransky** [comment]
Now in Nemtai and Nemati_2019
