### ISSUE TITLE
Make intTimes filter in next_target Overloadable

### ISSUE THREAD

**Issue by deanthedream** [dsavransky/EXOSIMS#89]
Currently the intTime filter will filter out targets longer than the allowed observing window. This should be more dynamic to allow filtering of observations that would be longer than this window should that kind of observation be desirable.

**Comment by dsavransky** [comment]
@deanthedream Has this been implemented in the 1.4 prerelease?  If yes, tag as 1.4 and close, otherwise tag to 1.5.

**Comment by deanthedream** [comment]
In v1.4-pre-release, filtering based on integration time is subdivided into two sections:

1. Filter by intCutOff where any optimally made observation would take longer than cutoff at default dMag
2. The get_ObsDetactionMaxIntTime method can be overloaded. This is used by default in the prototype SurveySimulation, next_target method
