### ISSUE TITLE
Observing Block implementation is still broken

### ISSUE THREAD

**Issue by dsavransky** [dsavransky/EXOSIMS#96]
Test case:  set mission portion to 0.5, missionDuration to 2 years, and OBduration to infinite.  The second year will be skipped because the OBendTimes is initialized to one year.  

This whole prototype should be rewritten.  Again.

**Comment by deanthedream** [comment]
Whenever OBduration = inf, I expect there to be 1 Observation block with length missionPortion*missionDuration. What other outcome should happen? (should the default max OBduration be specified as something smaller?)

**Comment by dsavransky** [comment]
I'm not fully sure what an infinite OBduration even represents with a mission portion of less than 1.  Maybe we should treat infinite OBdurations as the flag that tells timekeeping that the mission will be fully dynamically scheduled and its up to the scheduler to take care of everything?

**Comment by dsavransky** [comment]
I believe this is now fixed in the current 1.4 prerelease.  @deanthedream please comment and close as appropriate.

**Comment by deanthedream** [comment]
This issue is fixed in the v1.4-pre-release branch.
